ja_cable_home:
    path: /
    defaults: { _controller: JACableBundle:Advert:index }

ja_cable_add:
    path: /add
    defaults: { _controller: JACableBundle:Advert:add }

ja_cable_remove:
    path: /remove/{id}
    defaults: { _controller: JACableBundle:Advert:remove }
    requirements:
        id: \d+
    options:
        expose: true

ja_cable_view:
    path: /{id}
    defaults: { _controller: JACableBundle:Advert:view }
    requirements:
        id: \d+


ja_cable_json:
    path: /json/cables.json
    defaults: { _controller: JACableBundle:Advert:returnJson }