<?php

namespace JA\CableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CableRepository extends EntityRepository
{
}
